site_name: Плагин суммаризации Mattermost
site_description: Плагин для автоматической суммаризации сообщений в Mattermost с использованием LLM
site_author: EgorTarasov
site_url: https://egortarasov.github.io/summary

# Repository
repo_name: EgorTarasov/summary
repo_url: https://github.com/EgorTarasov/summary

# Docs directory
docs_dir: docs_site

# Configuration
theme:
  name: material
  language: ru
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.annotate
    - content.code.copy

# Plugins
plugins:
  - search:
      lang: ru

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

# Navigation
nav:
  - Главная: index.md
  - Руководство пользователя:
    - Установка: user-guide/installation.md
    - Настройка: user-guide/configuration.md
    - Использование: user-guide/usage.md
    - Команды: user-guide/commands.md
  - Руководство разработчика:
    # - Архитектура: dev-guide/architecture.md
    # - API: dev-guide/api.md
    - Тестирование: dev-guide/testing.md
    - Развертывание: dev-guide/deployment.md
  - Диаграммы:
    - Архитектура компонентов: diagrams/components.md
    - Поток данных: diagrams/data-flow.md
    - Процесс работы: diagrams/process.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EgorTarasov/summary
  version:
    provider: mike
